/** Inhalte für Wahrheit oder Pflicht, Kategorien und Regel-Ideen. `spicy` gilt nur im 18+-Modus. */

export interface WheelCard {
  /** Kurzer Titel, der im Rad steht (höchstens ca. 18 Zeichen). */
  title: string
  /** Vollständige Frage bzw. Aufgabe. */
  text: string
  spicy?: boolean
}

export interface Category {
  name: string
  spicy?: boolean
}

export const TRUTHS: readonly WheelCard[] = [
  { title: 'Peinlichster Moment', text: 'Was war dein peinlichster Moment in der Öffentlichkeit?' },
  { title: 'Größte Lüge', text: 'Welche ist die größte Lüge, die du je erzählt hast?' },
  { title: 'Heimlicher Schwarm', text: 'In wen warst du schon mal heimlich verliebt, ohne dass die Person es wusste?' },
  { title: 'Guilty Pleasure', text: 'Welches Lied, welche Serie oder welcher Film ist dein größtes Guilty Pleasure?' },
  { title: 'Betrunken', text: 'Was war das Dümmste, was du je betrunken getan hast?' },
  { title: 'Falsche Nachricht', text: 'Hast du schon mal eine Nachricht an die falsche Person geschickt? Was stand drin?' },
  { title: 'Geheimes Talent', text: 'Welches Talent hast du, von dem fast niemand hier weiß?' },
  { title: 'Schlimmstes Date', text: 'Erzähle von deinem schlimmsten Date.' },
  { title: 'Letzte Suche', text: 'Was hast du zuletzt gegoogelt, das du ungern zeigen würdest?' },
  { title: 'Gestohlen', text: 'Was hast du schon mal mitgehen lassen, auch wenn es nur eine Kleinigkeit war?' },
  { title: 'Peinliche App', text: 'Welche App auf deinem Handy ist dir am peinlichsten?' },
  { title: 'Krank gemacht', text: 'Wann hast du zuletzt krankgemacht, obwohl du gesund warst?' },
  { title: 'Neid', text: 'Auf wen in der Runde bist du ein kleines bisschen neidisch und warum?' },
  { title: 'Einsame Insel', text: 'Wen aus der Runde würdest du auf eine einsame Insel mitnehmen und wen nicht?' },
  { title: 'Zombie-Apokalypse', text: 'Wer in der Runde würde die Zombie-Apokalypse als Erstes nicht überleben?' },
  { title: 'Dümmste Ausrede', text: 'Was war deine dümmste Ausrede, die tatsächlich funktioniert hat?' },
  { title: 'Spitzname', text: 'Welchen peinlichen Spitznamen hattest du früher?' },
  { title: 'Bereuen', text: 'Was bereust du am meisten?' },
  { title: 'Unbeliebte Meinung', text: 'Welche unbeliebte Meinung vertrittst du, bei der dir alle widersprechen würden?' },
  { title: 'Kindheit', text: 'Was war das Peinlichste, das dir als Kind passiert ist?' },
  { title: 'Rot geworden', text: 'Wann bist du zuletzt vor Peinlichkeit rot geworden?' },
  { title: 'Bester Streich', text: 'Welchen Streich hast du jemandem schon mal gespielt?' },
  { title: 'Sprachnachricht', text: 'Welche Sprachnachricht hast du schon mal bereut abgeschickt zu haben?' },
  { title: 'Eifersucht', text: 'Wann warst du das letzte Mal richtig eifersüchtig?' },
  { title: 'Alter Chat', text: 'Lies die peinlichste Nachricht aus deinem Chatverlauf vor oder trinke 1 Schluck.' },
  { title: 'Schlimmster Job', text: 'Was war dein schlimmster Job oder deine schlimmste Prüfung?' },
  { title: 'Tabu-Thema', text: 'Über welches Thema sprichst du nie mit deinen Eltern?' },
  { title: 'Wen mögen', text: 'Welche Person in der Runde hat dich beim ersten Treffen am meisten überrascht?' },
  { title: 'Größte Angst', text: 'Wovor hast du am meisten Angst, auch wenn es albern klingt?' },
  { title: 'Letzte Träne', text: 'Wann hast du zuletzt geweint und warum?' },
  { title: 'Fake-Krank', text: 'Welche Verabredung hast du schon mal mit einer erfundenen Ausrede abgesagt?' },
  { title: 'Erster Eindruck', text: 'Was war dein erster Eindruck von der Person links neben dir?' },
  { title: 'Peinlicher Kauf', text: 'Was war dein peinlichster Kauf?' },
  { title: 'Fremdschämen', text: 'Bei welcher Aktion von dir schämst du dich bis heute fremd für dich selbst?' },
  { title: 'Größter Fehlkauf', text: 'Wofür hast du viel zu viel Geld ausgegeben?' },
  { title: 'Promi-Schwarm', text: 'Für welchen Promi hast du als Teenager geschwärmt?' },
  { title: 'Schlechteste Note', text: 'Was war deine schlechteste Note und wie kam es dazu?' },
  { title: 'Erwischt', text: 'Wobei wurdest du schon mal erwischt, als du dachtest, du wärst allein?' },
  { title: 'Stalken', text: 'Wessen Profil hast du zuletzt heimlich durchgescrollt?' },
  { title: 'Notlüge heute', text: 'Wann hast du zuletzt gelogen, und worum ging es?' },
  { title: 'Beste Freundschaft', text: 'Wem aus der Runde würdest du ein Geheimnis am ehesten anvertrauen?' },
  { title: 'Schlechte Angewohnheit', text: 'Welche schlechte Angewohnheit wirst du einfach nicht los?' },
  { title: 'Peinliche Playlist', text: 'Welches Lied in deiner Playlist würdest du niemals laut vorspielen?' },
  { title: 'Kindheitstraum', text: 'Was wolltest du als Kind werden, und was ist daraus geworden?' },
  { title: 'Blackout', text: 'Was ist das Letzte, woran du dich nach deinem schlimmsten Abend erinnerst?' },
  { title: 'Gelöschtes Foto', text: 'Welches Foto von dir sollte niemals jemand sehen?' },
  { title: 'Geschenk-Flop', text: 'Welches Geschenk fandest du schrecklich, hast dich aber artig bedankt?' },
  { title: 'Eltern angelogen', text: 'Was wissen deine Eltern bis heute nicht?' },
  { title: 'Größter Streit', text: 'Worum ging dein letzter richtig großer Streit?' },
  { title: 'Mutprobe', text: 'Was war das Mutigste oder Leichtsinnigste, das du je gemacht hast?' },
  { title: 'Schrägste Phobie', text: 'Vor welchem harmlosen Ding ekelst oder fürchtest du dich?' },
  { title: 'Lottogewinn', text: 'Was würdest du als Erstes tun, wenn du morgen im Lotto gewinnst?' },
  { title: 'Wer zahlt', text: 'Wer in der Runde schuldet dir noch etwas, Geld oder einen Gefallen?' },
  { title: 'Peinlicher Sturz', text: 'Wo hast du dich am spektakulärsten hingelegt?' },
  { title: 'Verschlafen', text: 'Was war der wichtigste Termin, den du je verschlafen hast?' },
  { title: 'Schlimmste Frisur', text: 'Was war deine schlimmste Frisur, und gibt es Beweisfotos?' },
  { title: 'Erster Kuss', text: 'Wie alt warst du bei deinem ersten Kuss, und wie war er?', spicy: true },
  { title: 'Schwarm hier', text: 'Wen aus dieser Runde würdest du am ehesten küssen?', spicy: true },
  { title: 'Flirtspruch', text: 'Was war dein dreistester Flirtspruch, und hat er funktioniert?', spicy: true },
  { title: 'Nacktbaden', text: 'Warst du schon mal nackt baden? Wo und mit wem?', spicy: true },
  { title: 'Vergebener Schwarm', text: 'Hast du schon mal für jemanden geschwärmt, der vergeben war?', spicy: true },
  { title: 'Bett-Panne', text: 'Was war dein peinlichstes Erlebnis im Bett?', spicy: true },
  { title: 'Fantasie', text: 'Hast du eine Fantasie, die du noch niemandem erzählt hast? Eine Andeutung reicht.', spicy: true },
  { title: 'Nachts an den Ex', text: 'Hast du schon mal nachts deinem Ex geschrieben?', spicy: true },
  { title: 'Dating-Apps', text: 'Welche Dating-Apps hast du ausprobiert, und was war das Schrägste?', spicy: true },
  { title: 'Knutschzahl', text: 'Mit wie vielen Menschen hast du schon geknutscht? Schätze ehrlich.', spicy: true },
  { title: 'Aufzug', text: 'Mit wem in der Runde würdest du am liebsten im Aufzug feststecken?', spicy: true },
  { title: 'Traumpartner', text: 'Welcher Promi wäre dein Traumpartner für eine Nacht?', spicy: true },
  { title: 'Erstes Mal', text: 'Wie war dein erstes Mal, in drei Worten?', spicy: true },
  { title: 'Ungewöhnlicher Ort', text: 'Was war der ungewöhnlichste Ort, an dem du intim warst?', spicy: true },
  { title: 'Größter Abturner', text: 'Was ist für dich der größte Abturner?', spicy: true },
  { title: 'Größter Anturner', text: 'Was macht dich sofort schwach?', spicy: true },
  { title: 'Beuteschema', text: 'Welcher Typ Mensch ist genau dein Beuteschema?', spicy: true },
  { title: 'One-Night-Stand', text: 'Hattest du schon mal einen One-Night-Stand? Wie kam es dazu?', spicy: true },
  { title: 'Erwischt worden', text: 'Wurdest du schon mal in einem intimen Moment erwischt?', spicy: true },
  { title: 'Körbe verteilt', text: 'Wem hast du den härtesten Korb gegeben, und wie?', spicy: true },
  { title: 'Korb kassiert', text: 'Was war der peinlichste Korb, den du je bekommen hast?', spicy: true },
  { title: 'Heißeste Person', text: 'Wer ist die attraktivste Person in dieser Runde?', spicy: true },
  { title: 'Freund-Schwarm', text: 'Fandest du schon mal den Partner oder die Partnerin eines Freundes attraktiv?', spicy: true },
  { title: 'Nacktfoto', text: 'Hast du schon mal ein freizügiges Foto verschickt oder bekommen?', spicy: true },
  { title: 'Schlechtester Kuss', text: 'Wer war dein schlechtester Kuss, und warum?', spicy: true },
  { title: 'Längste Durststrecke', text: 'Wie lang war deine längste Durststrecke?', spicy: true },
  { title: 'Ex zurück', text: 'Würdest du mit einem deiner Ex wieder etwas anfangen?', spicy: true },
  { title: 'Heimliche Vorliebe', text: 'Welche Vorliebe hast du, die man dir nicht ansieht?', spicy: true },
  { title: 'Dirty Talk', text: 'Was war das Peinlichste, das du oder jemand anderes im Bett gesagt hat?', spicy: true },
  { title: 'Fremdgeflirtet', text: 'Hast du schon mal geflirtet, obwohl du vergeben warst?', spicy: true },
  { title: 'Freundschaft Plus', text: 'Mit wem aus deinem Freundeskreis könntest du dir Freundschaft Plus vorstellen?', spicy: true },
  { title: 'Rollenspiel', text: 'Welches Kostüm oder welche Uniform findest du am anziehendsten?', spicy: true },
]

export const DARES: readonly WheelCard[] = [
  { title: 'Tierimitation', text: 'Imitiere ein Tier deiner Wahl, bis die Gruppe es errät.' },
  { title: 'Tanzeinlage', text: 'Tanze 20 Sekunden ohne Musik, als würde dich keiner sehen.' },
  { title: 'Planke', text: 'Halte 30 Sekunden die Planke oder trinke 1 Schluck.' },
  { title: 'Dialekt', text: 'Sprich in den nächsten zwei Zügen nur im Dialekt deiner Wahl.' },
  { title: 'Refrain', text: 'Singe den Refrain eines Liedes, das die Gruppe aussucht.' },
  { title: 'Hässliches Selfie', text: 'Mache das hässlichste Selfie, das du kannst, und zeige es der Runde.' },
  { title: 'Alphabet rückwärts', text: 'Sage das Alphabet rückwärts ab Z. Bei einem Fehler trinkst du 1 Schluck.' },
  { title: 'Lobrede', text: 'Halte eine 30-sekündige Lobrede auf einen Gegenstand im Raum.' },
  { title: 'Roboter', text: 'Sei bis zu deinem nächsten Zug ein Roboter: Sprich und bewege dich wie einer.' },
  { title: 'Andere Hand', text: 'Trinke bis zu deinem nächsten Zug nur mit der Hand, die du sonst nicht benutzt.' },
  { title: 'Massage', text: 'Gib der Person links neben dir 20 Sekunden lang eine Schultermassage.' },
  { title: 'Werbespot', text: 'Mache Werbung für das Glas in deiner Hand, als wäre es das beste Produkt der Welt.' },
  { title: 'Zungenbrecher', text: 'Sage dreimal schnell: „Fischers Fritz fischt frische Fische“. Bei einem Fehler trinkst du 1 Schluck.' },
  { title: 'Komplimente', text: 'Mache jeder Person in der Runde ein ehrliches Kompliment.' },
  { title: 'Pantomime', text: 'Stelle einen Filmtitel pantomimisch dar, bis die Gruppe ihn errät.' },
  { title: 'Siegerrede', text: 'Steige auf einen Stuhl und halte eine Siegerrede, als hättest du den Oscar gewonnen.' },
  { title: 'Fantasiesprache', text: 'Erkläre in einer erfundenen Sprache, wie man ein Bier einschenkt.' },
  { title: 'Blickkontakt', text: 'Halte 20 Sekunden Blickkontakt mit einer Person deiner Wahl, ohne zu lachen.' },
  { title: 'Nachrichtensprecher', text: 'Lies die Uhrzeit wie ein Nachrichtensprecher vor, bei dem etwas Schlimmes passiert ist.' },
  { title: 'Liegestütze', text: 'Mache 10 Liegestütze oder trinke 1 Schluck.' },
  { title: 'Spiegel', text: 'Eine Person deiner Wahl spiegelt 30 Sekunden lang jede deiner Bewegungen.' },
  { title: 'Neuer Spitzname', text: 'Gib der Person rechts neben dir einen Spitznamen, der bis zum Spielende gilt.' },
  { title: 'Schuhtausch', text: 'Tausche einen Schuh mit jemandem und trage ihn bis zum Spielende.' },
  { title: 'Zwei Wahrheiten', text: 'Erzähle drei Dinge über dich, davon ist eines gelogen. Die Gruppe rät, welches.' },
  { title: 'Opernstimme', text: 'Singe deinen Namen in Opernstimme.' },
  { title: 'Telefonjoker', text: 'Rufe jemanden an und frage ohne Erklärung: „Wie spät ist es auf dem Mond?“' },
  { title: 'Eiswürfel', text: 'Halte einen Eiswürfel, bis er geschmolzen ist, oder trinke 1 Schluck.' },
  { title: 'Standup', text: 'Erzähle einen Witz. Lacht keiner, trinkst du 1 Schluck.' },
  { title: 'Zeitlupe', text: 'Bewege dich bis zu deinem nächsten Zug nur in Zeitlupe.' },
  { title: 'Auf einem Bein', text: 'Stehe bis zu deinem nächsten Zug auf einem Bein oder trinke 1 Schluck.' },
  { title: 'Akzent', text: 'Sprich bis zu deinem nächsten Zug mit französischem Akzent.' },
  { title: 'Luftgitarre', text: 'Spiele 20 Sekunden lang ein episches Luftgitarren-Solo.' },
  { title: 'Wettervorhersage', text: 'Präsentiere die Wettervorhersage für das Zimmer, in dem ihr sitzt.' },
  { title: 'Kniebeugen', text: 'Mache 15 Kniebeugen oder trinke 1 Schluck.' },
  { title: 'Catwalk', text: 'Laufe einmal wie ein Model über den Laufsteg durch den Raum.' },
  { title: 'Rap', text: 'Rappe vier Zeilen über die Person rechts neben dir.' },
  { title: 'Kellner', text: 'Bediene bis zu deinem nächsten Zug die Runde und schenke jedem nach, der es möchte.' },
  { title: 'Flüstern', text: 'Sprich bis zu deinem nächsten Zug nur im Flüsterton.' },
  { title: 'Sportkommentator', text: 'Kommentiere 30 Sekunden lang wie ein Sportreporter, was die Runde gerade tut.' },
  { title: 'Promi-Imitation', text: 'Imitiere einen Promi, bis die Gruppe ihn errät.' },
  { title: 'Emoji-Gesicht', text: 'Stelle drei Emojis mit dem Gesicht dar, die Gruppe rät.' },
  { title: 'Babysprache', text: 'Sprich bis zu deinem nächsten Zug nur in Babysprache.' },
  { title: 'Wortverbot', text: 'Du darfst bis zu deinem nächsten Zug nicht „ja“ und „nein“ sagen. Pro Fehler 1 Schluck.' },
  { title: 'Trinkspruch', text: 'Bringe einen feierlichen Trinkspruch auf die Person gegenüber aus.' },
  { title: 'Letztes Foto', text: 'Zeige der Runde das letzte Foto in deiner Galerie oder trinke 1 Schluck.' },
  { title: 'Akku-Check', text: 'Wer in der Runde den niedrigsten Akkustand hat, trinkt mit dir zusammen 1 Schluck.' },
  { title: 'Statue', text: 'Die Person links bringt dich in eine Pose, die du 30 Sekunden hältst.' },
  { title: 'Gurgeln', text: 'Gurgle die Melodie eines Liedes, bis die Gruppe es errät.' },
  { title: 'Reim-Zwang', text: 'Jeder deiner Sätze muss sich bis zu deinem nächsten Zug reimen.' },
  { title: 'Märchenstunde', text: 'Erzähle in 30 Sekunden ein Märchen, in dem alle aus der Runde vorkommen.' },
  { title: 'Schere Stein Papier', text: 'Spiele gegen die Person rechts Schere, Stein, Papier. Wer verliert, trinkt 1 Schluck.' },
  { title: 'Daumenkrieg', text: 'Fordere jemanden zum Daumenkrieg heraus. Wer verliert, trinkt 1 Schluck.' },
  { title: 'Blinzel-Duell', text: 'Starre eine Person deiner Wahl an. Wer zuerst blinzelt, trinkt 1 Schluck.' },
  { title: 'Status', text: 'Lass die Gruppe einen harmlosen Satz bestimmen, den du als Status postest, oder trinke 2 Schlücke.' },
  { title: 'Verkäufer', text: 'Verkaufe der Person gegenüber in 30 Sekunden deinen linken Schuh.' },
  { title: 'Wahlkampfrede', text: 'Halte eine Wahlkampfrede: Warum solltest du König oder Königin der Runde werden?' },
  { title: 'Flirten', text: 'Flirte 20 Sekunden lang mit einer Person deiner Wahl.', spicy: true },
  { title: 'Handkuss', text: 'Gib der Person rechts neben dir einen Handkuss.', spicy: true },
  { title: 'Anmachspruch', text: 'Bringe die Person links von dir mit einem Anmachspruch zum Lachen.', spicy: true },
  { title: 'Sexy Tanz', text: 'Tanze 15 Sekunden lang so verführerisch du kannst.', spicy: true },
  { title: 'Verführerische Stimme', text: 'Lies die Zutatenliste einer Verpackung mit deiner verführerischsten Stimme vor.', spicy: true },
  { title: 'Liebesgedicht', text: 'Dichte ein Liebesgedicht mit zwei Zeilen für die Person gegenüber.', spicy: true },
  { title: 'Schlafzimmerblick', text: 'Setze deinen verführerischsten Blick auf, bis die Gruppe applaudiert.', spicy: true },
  { title: 'Charme-Offensive', text: 'Mache der Person gegenüber das charmanteste Kompliment, das dir einfällt.', spicy: true },
  { title: 'Kleidungstausch', text: 'Tausche ein Kleidungsstück (Jacke, Mütze, Socke) mit einer Person deiner Wahl.', spicy: true },
  { title: 'Wangenkuss', text: 'Gib einer Person deiner Wahl einen Kuss auf die Wange.', spicy: true },
  { title: 'Massage-Duell', text: 'Gib der Person gegenüber eine 15-sekündige Handmassage.', spicy: true },
  { title: 'Kuss-Wette', text: 'Die Gruppe sagt, wen du für 5 Sekunden fest umarmen musst.', spicy: true },
  { title: 'Schoßplatz', text: 'Setze dich bis zu deinem nächsten Zug auf den Schoß einer Person deiner Wahl.', spicy: true },
  { title: 'Nackenkuss', text: 'Gib einer Person deiner Wahl einen Kuss auf den Nacken oder trinke 2 Schlücke.', spicy: true },
  { title: 'Ohrflüstern', text: 'Flüstere der Person links etwas Verführerisches ins Ohr.', spicy: true },
  { title: 'Lapdance', text: 'Gib einem Stuhl 15 Sekunden lang einen Lapdance.', spicy: true },
  { title: 'Kleidungsstück', text: 'Lege ein Kleidungsstück deiner Wahl ab oder trinke 2 Schlücke.', spicy: true },
  { title: 'Bodyshot', text: 'Trinke einen Schluck aus der hohlen Hand einer Person deiner Wahl.', spicy: true },
  { title: 'Stöhnen', text: 'Stöhne den Namen der Person gegenüber so überzeugend du kannst.', spicy: true },
  { title: 'Kuss-Ranking', text: 'Sortiere die Runde danach, wen du am liebsten küssen würdest.', spicy: true },
  { title: 'Füttern', text: 'Lass dich von einer Person deiner Wahl mit einem Snack füttern.', spicy: true },
  { title: 'Tinder-Bio', text: 'Schreibe laut eine Dating-Bio für die Person rechts neben dir.', spicy: true },
  { title: 'Verführung', text: 'Versuche 20 Sekunden lang, die Person gegenüber nur mit Blicken zu verführen.', spicy: true },
  { title: 'Dirty Talk light', text: 'Beschreibe mit verführerischer Stimme, wie man ein Spiegelei brät.', spicy: true },
  { title: 'Händchenhalten', text: 'Halte bis zu deinem nächsten Zug die Hand der Person links neben dir.', spicy: true },
  { title: 'Lippenleser', text: 'Forme lautlos einen frechen Satz, die Person gegenüber muss ihn erraten.', spicy: true },
  { title: 'Sexy Selfie', text: 'Mache dein verführerischstes Selfie und zeige es der Runde.', spicy: true },
  { title: 'Kuscheln', text: 'Kuschle 20 Sekunden lang mit einer Person deiner Wahl.', spicy: true },
  { title: 'Eiswürfel-Pass', text: 'Gib einen Eiswürfel nur mit dem Mund an die Person rechts weiter, oder ihr trinkt beide.', spicy: true },
  { title: 'Striptease light', text: 'Ziehe eine Socke so verführerisch aus, wie du kannst.', spicy: true },
  { title: 'Kussmund', text: 'Gib jeder Person in der Runde einen Luftkuss mit Ansage.', spicy: true },
  { title: 'Herzschlag', text: 'Lege dein Ohr 10 Sekunden an die Brust einer Person deiner Wahl und zähle den Herzschlag.', spicy: true },
]

export const CATEGORIES: readonly Category[] = [
  { name: 'Automarken' },
  { name: 'Biermarken' },
  { name: 'Fußballvereine' },
  { name: 'Hauptstädte' },
  { name: 'Cocktails' },
  { name: 'Spirituosen' },
  { name: 'Süßigkeiten' },
  { name: 'Supermärkte' },
  { name: 'Käsesorten' },
  { name: 'Pizzabeläge' },
  { name: 'Disney-Filme' },
  { name: 'Bands' },
  { name: 'Fast-Food-Ketten' },
  { name: 'Obstsorten' },
  { name: 'Bundesländer' },
  { name: 'Zootiere' },
  { name: 'Superhelden' },
  { name: 'Sportarten' },
  { name: 'Netflix-Serien' },
  { name: 'Deutsche Städte' },
  { name: 'Berufe' },
  { name: 'Gewürze' },
  { name: 'Dinge im Badezimmer' },
  { name: 'Handymarken' },
  { name: 'Eissorten' },
  { name: 'Brettspiele' },
  { name: 'Videospiele' },
  { name: 'Zeichentrickfiguren' },
  { name: 'Musikinstrumente' },
  { name: 'Modemarken' },
  { name: 'Europäische Länder' },
  { name: 'Flüsse' },
  { name: 'Hunderassen' },
  { name: 'Schauspieler' },
  { name: 'Rapper' },
  { name: 'Schlagerstars' },
  { name: 'Fußballspieler' },
  { name: 'Formel-1-Fahrer' },
  { name: 'Dinge im Kühlschrank' },
  { name: 'Dinge im Büro' },
  { name: 'Dinge am Strand' },
  { name: 'Dinge im Werkzeugkasten' },
  { name: 'Möbelstücke' },
  { name: 'Nudelsorten' },
  { name: 'Gemüsesorten' },
  { name: 'Brotaufstriche' },
  { name: 'Chipssorten' },
  { name: 'Energydrinks' },
  { name: 'Weinsorten' },
  { name: 'Schnäpse' },
  { name: 'Shots' },
  { name: 'Trinkspiele' },
  { name: 'Kartenspiele' },
  { name: 'Schulfächer' },
  { name: 'Studiengänge' },
  { name: 'Sprachen' },
  { name: 'Währungen' },
  { name: 'Planeten und Monde' },
  { name: 'Harry-Potter-Figuren' },
  { name: 'Marvel-Figuren' },
  { name: 'Star-Wars-Figuren' },
  { name: 'Pokémon' },
  { name: 'Simpsons-Figuren' },
  { name: 'Deutsche Filme' },
  { name: 'Horrorfilme' },
  { name: 'Castingshows' },
  { name: 'Streamingdienste' },
  { name: 'Soziale Netzwerke' },
  { name: 'YouTuber und Streamer' },
  { name: 'Festivals' },
  { name: 'Tanzstile' },
  { name: 'Musikrichtungen' },
  { name: 'Feiertage' },
  { name: 'Urlaubsländer' },
  { name: 'Inseln' },
  { name: 'Fluggesellschaften' },
  { name: 'Baumärkte' },
  { name: 'Drogeriemärkte' },
  { name: 'Körperteile' },
  { name: 'Farben' },
  { name: 'Vornamen mit A' },
  { name: 'Ausreden fürs Zuspätkommen' },
  { name: 'Gründe zum Anstoßen' },
  { name: 'Dinge, die man verliert' },
  { name: 'Dinge im Schlafzimmer', spicy: true },
  { name: 'Dating-Apps', spicy: true },
  { name: 'Kosenamen', spicy: true },
  { name: 'Berühmte Liebespaare', spicy: true },
  { name: 'Orte zum Knutschen', spicy: true },
  { name: 'Flirtsprüche', spicy: true },
  { name: 'Stellungen', spicy: true },
  { name: 'Sexspielzeug', spicy: true },
  { name: 'Verhütungsmittel', spicy: true },
  { name: 'Abturner', spicy: true },
  { name: 'Anturner', spicy: true },
  { name: 'Orte für ein Schäferstündchen', spicy: true },
  { name: 'Schimpfwörter', spicy: true },
  { name: 'Erotikfilme und -serien', spicy: true },
  { name: 'Reizwäsche', spicy: true },
  { name: 'Rollenspiele', spicy: true },
  { name: 'Dinge, die man im Bett sagt', spicy: true },
  { name: 'Gründe für eine Trennung', spicy: true },
  { name: 'Ausreden nach einem One-Night-Stand', spicy: true },
  { name: 'Promis, die heiß sind', spicy: true },
  { name: 'Wörter für betrunken', spicy: true },
  { name: 'Wörter für Sex', spicy: true },
  { name: 'Peinliche Dinge beim ersten Date', spicy: true },
  { name: 'Red Flags', spicy: true },
  { name: 'Dinge im Nachtschrank', spicy: true },
  { name: 'Körperteile zum Küssen', spicy: true },
  { name: 'Fetische', spicy: true },
  { name: 'Kondommarken', spicy: true },
  { name: 'Dinge, die man nackt nicht tun sollte', spicy: true },
  { name: 'Dating-Fails', spicy: true },
]

/** Anregungen für die 9, wenn jemand eine Regel erfinden will. */
export const RULE_IDEAS: readonly string[] = [
  'Wer „trinken“ sagt, trinkt selbst einen Schluck.',
  'Niemand sagt Namen. Alle sagen nur „du“.',
  'Beim Anstoßen muss man sich in die Augen sehen.',
  'Wer das Handy anfasst, trinkt einen Schluck.',
  'Getrunken wird nur mit der linken Hand.',
  'Wer lacht, trinkt einen Schluck.',
  'Wer aufs Klo will, trinkt vorher einen Schluck.',
  'Fluchen kostet einen Schluck.',
  'Vor jedem Schluck sagt man „Prost“ in einer anderen Sprache.',
  'Niemand zeigt mit dem Finger. Wer es tut, trinkt.',
  'Daumenregel: Wer den Daumen zuletzt auf den Tisch legt, trinkt.',
  'Jeder Satz endet mit „Alter“.',
  'Der Vorname des Nachbarn zur Linken darf nicht gesagt werden.',
  'Wer sein Glas abstellt, ohne zu trinken, trinkt einen Schluck.',
]

/** Pool je nach Spicy-Schalter: ohne Spicy nur die normalen Einträge. */
export function contentPool<T extends { spicy?: boolean }>(items: readonly T[], spicy: boolean): T[] {
  return items.filter((item) => spicy || !item.spicy)
}
